/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_shetj_sdk_ffmepg_FFmpegKit */

#ifndef _Included_me_shetj_sdk_ffmepg_FFmpegKit
#define _Included_me_shetj_sdk_ffmepg_FFmpegKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_shetj_sdk_ffmepg_FFmpegKit
 * Method:    checkFFmpeg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_shetj_sdk_ffmepg_FFmpegKit_checkFFmpeg
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
